[project]
name = 'Galactic-Ecosystem-Symbiosis-Optimizer'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.ecosystem-data]
path = 'contracts/ecosystem-data.clar'
clarity_version = 2
epoch = 2.5

[contracts.symbiosis-proposal]
path = 'contracts/symbiosis-proposal.clar'
clarity_version = 2
epoch = 2.5

[contracts.symbiotic-pair-nft]
path = 'contracts/symbiotic-pair-nft.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
